eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
  
feign:
  hystrix:
    enabled: true
    
spring:
  zipkin:
    base-url: http://localhost:8080
