spring:
  application:
    name: srv2-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763


hystrix:
  enabled: true
  shareSecurityContext: true


security:
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true #必须要有 否则获取不到user信息
      user-info-uri:  http://uaa-server/uaa/user # auth-server 是注册到eureka的服务名称
      prefer-token-info: false # 不使用/oauth/check_token,因为不能负载均衡 使用在auth-server端实现的 /user api.